### PR TITLE
Update ipmi_intf.h

### PR DESCRIPTION
**Pull request by patch-work**
```
ipmi_fru.c:528:26: warning: implicit declaration of function 'ipmi_intf_get_max_request_data_size' is invalid in C99 [-Wimplicit-function-declaration]
                uint16_t max_rq_size = ipmi_intf_get_max_request_data_size(intf);
                                       ^
ipmi_fru.c:698:26: warning: implicit declaration of function 'ipmi_intf_get_max_response_data_size' is invalid in C99 [-Wimplicit-function-declaration]
                uint16_t max_rs_size = ipmi_intf_get_max_response_data_size(intf) - 1;
                                       ^

```

### CODE REVIEW

**Comment by AlexanderAmelkin** [comment]
Please make commit messages more verbose, explaining the reason for the change.

**Comment by patch-work** [comment]
Please find the reason for the change in my original comment.

**Comment by AlexanderAmelkin** [comment]
> Please find the reason for the change in my original comment.

That's not the matter of me not understanding the reason. It's the matter of commit messages lacking it and generally being out of sync with the contribution rules. The link to this PR is not recorded by git and eventually will be lost, leaving future contributors wondering what the commit was for. The reason may be quite obvious as in this case, or completely incomprehensible. Hence, there is a rule to make commit log meaningful. It is obvious from the commit log that you're changing ipmi_intf.h header, there is no need to repeat that in the commit log. The reason WHY you're doing so is a mystery to anyone looking at the log.

A message like this would be great:

```
fru: Fix compilation warnings

The ipmi_fru module uses public functions from ipmi_intf that lack
declarations in the corresponding header. This commit fixes that.

Signed-off-by: Patch Adam <your@email>
```

Please see https://github.com/ipmitool/ipmitool/wiki#how-to-contribute

Besides, the commit that updates `create_pen_list` script is unrelated to this PR and also lacks the reasoning (and/or a reference to an issue that it fixes).

**Comment by AlexanderAmelkin** [comment]
Properly fixed in 1724b031b3c9d011082a69525ad527e15e54bfc5. Closing.

**Pull request closed without merging**
